# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       charger-control

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Charger Control
Version:    0.2
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://openrepos.net/content/xkr47/charger-control
Source0:    %{name}-%{version}.tar.bz2
Source100:  charger-control.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  desktop-file-utils

%description
Charger control is designed for the original Jolla Phone and allows you to control how the battery is charged/discharged when a USB cable is connected.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%pre
# >> pre
# see https://fedoraproject.org/wiki/Packaging:ScriptletSnippets
# if upgrade, run before new package is installed and before old package is uninstalled
grep "^charger-control:" /etc/group > /dev/null || groupadd charger-control
# << pre

%preun
# >> preun
# if upgrade, this is run after new package installation is complete but before old package is uninstalled
# systemd parts taken partially from http://cgit.freedesktop.org/systemd/systemd/tree/src/core/macros.systemd.in
if [ $1 -eq 0 ] ; then
# Package removal, not upgrade
systemctl --no-reload disable charger-control-permissions.service || :
systemctl stop charger-control-permissions.service || :
fi
# << preun

%post
# >> post
# if upgrade, run after new package is installed but before old package is uninstalled
if [ $1 -eq 1 ] ; then
# Initial installation
systemctl enable /usr/lib/systemd/user/charger-control-permissions.service
systemctl start charger-control-permissions.service
else
# Package upgrade
systemctl reenable /usr/lib/systemd/user/charger-control-permissions.service
fi
# << post

%postun
# >> postun
# if upgrade, this is run after new package installation and old package uninstallation is complete
systemctl daemon-reload >/dev/null 2>&1 || :
if [ $1 -eq 0 ] ; then
# Package removal, not upgrade
! grep "^charger-control:" /etc/group > /dev/null || groupdel charger-control
fi
if [ $1 -ge 1 ] ; then
# Package upgrade, not uninstall
systemctl restart charger-control-permissions.service || :
fi
# << postun

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_libdir}/systemd/user/charger-control-permissions.service
%{_libexecdir}/charger-control-permissions.sh
%attr(2755, root, charger-control) %{_bindir}/%{name}
%attr(700, root, root) %{_libexecdir}/%{name}-permissions.sh
